### ISSUE TITLE
Error occurred while uploading video.

### ISSUE THREAD

**Issue by danny900714** [KMU-Dev/video-uploader#3]
Error Log:
2020-12-07T17:10:00.001424793+08:00 MainService start.
2020-12-07T17:10:02.211557796+08:00 Upload video "Histology Week 14.mp4" to "Histology" folder...
2020-12-07T17:10:02.219721701+08:00 Error: No refresh token is set.
2020-12-07T17:10:02.219766334+08:00     at OAuth2Client.refreshTokenNoCache (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:162:19)
2020-12-07T17:10:02.219785695+08:00     at OAuth2Client.refreshToken (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:143:25)
2020-12-07T17:10:02.219799345+08:00     at OAuth2Client.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:259:28)
2020-12-07T17:10:02.219811050+08:00     at OAuth2Client.requestAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:332:34)
2020-12-07T17:10:02.219822720+08:00     at OAuth2Client.request (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:326:25)
2020-12-07T17:10:02.219833675+08:00     at createAPIRequestAsync (/app/node_modules/googleapis-common/build/src/apirequest.js:273:31)
2020-12-07T17:10:02.219847517+08:00     at Object.createAPIRequest (/app/node_modules/googleapis-common/build/src/apirequest.js:53:16)
2020-12-07T17:10:02.219859053+08:00     at Resource$Files.create (/app/node_modules/googleapis/build/src/apis/drive/v3.js:658:44)
2020-12-07T17:10:02.219870011+08:00     at UploadService.uploadVideo (/app/service/UploadService.js:35:36)
2020-12-07T17:10:02.219884111+08:00     at runMicrotasks (<anonymous>)
2020-12-07T17:10:02.615094228+08:00 MainService finished without any error.

**Comment by danny900714** [comment]
Update how typeorm save new credential.
